import postgres from 'postgres'

export type BoardCreation = {
	createdAt: string
	grid: string
	id: number
}

type BoardRow = {
	created_at: string
	grid: string
	id: number
}

// Connections are lazy: Next imports this module while building, before Railway injects runtime variables.
export const sql = postgres(process.env.DATABASE_URL || 'postgres://localhost:5432/maker', {
	max: 5
})
let initialized: Promise<void> | undefined

export const initializeBoard = (): Promise<void> => {
	initialized ??= (async () => {
		if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required')
		await sql`CREATE TABLE IF NOT EXISTS creations (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			grid TEXT NOT NULL UNIQUE,
			created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
			hidden INTEGER NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1))
		)`
		await sql`CREATE TABLE IF NOT EXISTS snake_score (
			id INTEGER PRIMARY KEY CHECK (id = 1),
			score INTEGER NOT NULL DEFAULT 0 CHECK (score BETWEEN 0 AND 900)
		)`
		await sql`INSERT INTO snake_score (id, score) VALUES (1, 0) ON CONFLICT (id) DO NOTHING`
	})().catch(error => {
		initialized = undefined
		throw error
	})
	return initialized
}

const serialize = (row: BoardRow): BoardCreation => ({
	createdAt: row.created_at,
	grid: row.grid,
	id: row.id
})

export const listCreations = async (limit = 90): Promise<BoardCreation[]> => {
	await initializeBoard()
	const rows = await sql<
		BoardRow[]
	>`SELECT id, grid, created_at FROM creations WHERE hidden = 0 ORDER BY id DESC LIMIT ${limit}`
	return rows.map(serialize)
}

export const findCreation = async (grid: string): Promise<BoardCreation | null> => {
	await initializeBoard()
	const rows = await sql<BoardRow[]>`SELECT id, grid, created_at FROM creations WHERE grid = ${grid}`
	return rows[0] ? serialize(rows[0]) : null
}

export const addCreation = async (
	grid: string,
	hidden: boolean
): Promise<{ created: boolean; creation: BoardCreation }> => {
	await initializeBoard()
	const inserted = await sql<
		BoardRow[]
	>`INSERT INTO creations (grid, hidden) VALUES (${grid}, ${hidden ? 1 : 0}) ON CONFLICT (grid) DO NOTHING RETURNING id, grid, created_at`
	const creation = inserted[0] ? serialize(inserted[0]) : await findCreation(grid)
	if (!creation) throw new Error('Failed to save creation')
	return { created: inserted.length > 0, creation }
}

// Toggling a few pixels of a hidden icon and publishing again is the usual way around the model.
const NEAR = 0.08

/** Whether a hidden icon of the same size differs from this grid in at most 8% of its cells. */
export const nearHidden = async (grid: string): Promise<boolean> => {
	await initializeBoard()
	const tolerance = Math.max(2, Math.round(grid.length * NEAR))
	const rows = await sql<
		{ grid: string }[]
	>`SELECT grid FROM creations WHERE hidden = 1 AND length(grid) = ${grid.length}`
	return rows.some(row => {
		let distance = 0
		for (let index = 0; index < grid.length && distance <= tolerance; index++) {
			if (grid[index] !== row.grid[index]) distance++
		}
		return distance <= tolerance
	})
}

export const listAllCreations = async (): Promise<(BoardCreation & { hidden: boolean })[]> => {
	await initializeBoard()
	const rows = await sql<
		(BoardRow & { hidden: number })[]
	>`SELECT id, grid, created_at, hidden FROM creations ORDER BY id`
	return rows.map(row => ({ ...serialize(row), hidden: row.hidden === 1 }))
}

export const setHidden = async (id: number, hidden: boolean): Promise<void> => {
	await initializeBoard()
	await sql`UPDATE creations SET hidden = ${hidden ? 1 : 0} WHERE id = ${id}`
}

export const snakeHighScore = async (): Promise<number> => {
	await initializeBoard()
	const rows = await sql<{ score: number }[]>`SELECT score FROM snake_score WHERE id = 1`
	return rows[0]?.score ?? 0
}

export const recordSnakeScore = async (
	score: number
): Promise<{ highScore: number; newRecord: boolean }> => {
	await initializeBoard()
	const updated = await sql<
		{ score: number }[]
	>`UPDATE snake_score SET score = ${score} WHERE id = 1 AND score < ${score} RETURNING score`
	return {
		highScore: updated[0]?.score ?? (await snakeHighScore()),
		newRecord: updated.length === 1
	}
}
